name: dmpipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - tqdm=4.65.0
  - rasterio=1.3.7
  - pandas=2.0.3
  - geopandas=0.13.2
  - pip=22.3.1
  - gdal
  - earthengine-api=0.1.357
  - PyDrive=1.3.1
  - python-dotenv=1.0.0
  - setuptools=65.5.0
  - scipy=1.10.1
  - contextily=1.5.1
  - matplotlib-scalebar=0.8.1
  - folium=0.15.1